export class PflegeRechnerFields {
    static fields = {

        calculationFields : {
            field_1_default_GanzwaescheInBadDuscheOderAmLavabo: 40,
            field_2_default_GanzwaescheBettlaegerigeKlientIn: 40,
            field_3_default_TeilwaescheAmLavabo: 26,
            field_4_TeilwaescheImBett: 20,
            field_5_default_IntimpflegeImBettOderAmLavabo: 15,
            field_6_default_HaareWaschen: 15,
            field_7_default_FingernaegelSchneiden: 15,
            field_8_default_FussnaegelSchneiden: 15,
            field_9_default_TotalZahnpflege2xTaeglich: 5,
            field_10_default_RasurInKombinationMitGanzOderTeilwaesche: 10,
            field_185_default_AnUndAusziehen: 15,
            field_186_default_AufstehenUndHinlegen: 5,
            field_187_default_LagerungImBett: 8,
            field_188_default_Dekubitusprophylaxe: 20,
            field_189_default_KompressionsstruempfeOderVerband: 10,
            field_190_default_BeiEssenTrinkenUnterstuetzen: 10,
            field_191_default_HilfeBeimGehenUndStehen: 8,
            field_192_default_HilfeBeimToilettengang: 10,
            field_98_mwst: 8.1,
        },

        calculationResults : {
            
            field_138_inkontinenz : "",
            field_83_kognitive_probleme : "",
            field_25_bewegungseinschraenkung : "",
            field_139_kompressionsstrumpfe : "",
            field_137_lage_aendern : "",
            field_136_aufstehen_und_hinlegen : "",
            field_23_geschlecht: "",
            field_24_mobilitaet: "",
            field_78_krankenkasse: "",
	        field_76_kanton: "",
            field_999_krankenkasse_kann_abgerechnet_werden: "Nein",
            field_246_kanton_kann_abgerechnet_werden: "Nein",
            field_153_koerperpflege_im_bett: "Nein",
            field_184_pflegezeit_in_min_pro_tag_Ganzwasche_im_Bett: 0,
            field_194_pflegezeit_in_min_pro_tag_Teilwasche_im_bett: 0,
            field_143_Ganzwaesche_im_bad: "Nein",
            field_193_pflegezeit_in_min_pro_tag_Ganzwaesche_im_bad: 0,
            field_152_teilwaesche_im_bad: "Nein",
            field_195_pflegezeit_in_min_pro_tag_Teilwaesche_im_bad: 0,
            field_174_haare_waschen: "Nein",
            field_196_pflegezeit_in_min_pro_tag_haare_waschen: 0,
            field_157_zahnpflege: "Nein",
            field_197_pflegezeit_in_min_pro_tag_zahnpflege: 0,
            field_210_Fingernaegel_schneiden: "Nein",
            field_209_pflegezeit_in_min_pro_tag_Fingernaegel_schneiden: 0,
            field_161_Zehnaegel_schneiden: "Nein",
            field_198_pflegezeit_in_min_pro_tag_Zehnaegel_schneiden: 0,
            field_165_Begleitung_Toilettengang: "Nein",
            field_199_pflegezeit_in_min_pro_tag_Begleitung_Toilettengang: 0,
            field_173_Intimpflege: "Nein",
            field_200_pflegezeit_in_min_pro_tag_Intimpflege: 0,
            field_166_HilfeBeimGehenUndStehen: "Nein",
            field_201_pflegezeit_in_min_pro_tag_HilfeBeimGehenUndStehen: 0,
            field_167_LagerungImBett: "Nein",
            field_202_pflegezeit_in_min_pro_tag_LagerungImBett: 0,
            field_168_Hilfe_beim_Aufstehen_und_Hinlegen: "Nein",
            field_203_pflegezeit_in_min_pro_tag_Hilfe_beim_Aufstehen_und_Hinlegen: 0,
            field_175_Hilfe_beim_Hilfe_beim_An_und_Ausziehen: "Nein",
            field_204_pflegezeit_in_min_pro_tag_Hilfe_beim_Hilfe_beim_An_und_Ausziehen: 0,
            field_169_Dekubitusprophylaxe: "Nein",
            field_205_pflegezeit_in_min_pro_tag_Dekubitusprophylaxe: 0,
            field_170_Unterstutzung_Essen_und_Trinken: "Nein",
            field_206_pflegezeit_in_min_pro_tag_Unterstutzung_Essen_und_Trinken: 0,
            field_171_Rasieren: "Nein",
            field_207_pflegezeit_in_min_pro_tag_Rasieren: 0,
            field_172_Kompressionsstrumpfe: "Nein",
            field_208_pflegezeit_in_min_pro_tag_Kompressionsstrumpfe: 0,
            field_81_Summe_durchschnittliche_pflegeleistungen_in_Minuten_an_30_Tagen_vor_Abzug_fr_Korrekturen_Demenzfaktor: 0,
            field_179_Korrektur_bei_Toilettengang_und_Hilfe_beim_Gehen: 0,
            field_180_Korrektur_bei_Ganzwasche_und_An_Ausziehen: 0,
            field_182_Korrektur_bei_Teilwasche_und_An_Ausziehen: 0,
            field_181_Korrektur_bei_Ganzwasche_und_Kompressionsstrumpfe: 0,
            field_216_Summe_Korrekturzeiten: 0,
            field_217_Summe_durchschnittliche_pflegeleistungen_in_Minuten_an_30_Tagen : 0,

            field_81_Summe_Pflegeleistung_in_Minuten_an_30_Tagen_vor_abzug_demenz : 0, 


            field_176_KorrekturFaktor_bei_schwerer_Demenz_Gehfahigkeit : 1,
            field_177_KorrekturFaktor_bei_schwerer_Demenz_Rumpf_Arme : 1,
            field_178_Ergebnis_KorrekturFaktor_Demenz : 1,
            field_211_Summe_durchschnittliche_Pflegeleistungen_in_Minuten_pro_Tag_vor_CAP_bei_220_Minuten : 1.0,
            field_218_durchschnittliche_Pflegeleistungen_in_Minuten_pro_Tag : 0,
            field_212_Summe_durchschnittliche_Pflegeleistungen_in_Stunden_pro_Tag : 0,
            field_259_Definition_unterer_Bereich_Pflegezeiten : 0,
            field_260_Definition_oberer_Bereich_Pflegezeiten : 0,
            field_261_Bruttolohn : 0,



        salutation : "", 
		vorname: "",
		nachname : "",
		phone : "",
		email : "",
        }
    };

}